[supervisord]
nodaemon=true
loglevel=info

[program:smtpd]
command=/opt/halon/sbin/smtpd -f

[program:expurgate]
command=/usr/bin/expurgate-spamd --no-daemonize --config /etc/expurgate-spamd/expurgate-spamd.conf
